name: bandit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
          configfile: 'bandit.yaml'
          confidence: 'high'
