## This runs bandit checks on all jupyter notebooks and python files
name: BanditEverything

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_call:


jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get changed notebooks
        id: get-changed-notebooks
        uses: tj-actions/changed-files@v44.5.5
        with:
          separator: " " # nbconvert accepts space separated file list
          safe_output: false #set to false because we are using an environment variable to store the output and avoid command injection.
          files: |
            **/*.ipynb    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install nbconvert
        if: steps.get-changed-notebooks.outputs.any_changed == 'true'
        run: pip install nbconvert
      - name: Convert Jupyter notebooks
        if: steps.get-changed-notebooks.outputs.any_changed == 'true'
        env:
          ADDED_FILES: ${{ steps.get-changed-notebooks.outputs.added_files }}     
        run: jupyter nbconvert --allow-errors --sanitize-html --to script $ADDED_FILES        
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
          confidence: 'high'
          exclude: "*.txt,.git,.github,.eggs,*.egg,.gitignore,*.yml"

